# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170518_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
