# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170518_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_fav',
        ),
    ]
