# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_song_is_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='app_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
